# Generated by Django 6.0.4 on 2026-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Mozo'), (4, 'Cocinero')], default=2),
        ),
    ]
