# Generated by Django 6.0.4 on 2026-04-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_task_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='important',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='title',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Pedido creado'), ('PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='CREADO', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(choices=[(1, 'Mesa 1'), (2, 'Mesa 2'), (3, 'Mesa 3'), (4, 'Mesa 4'), (5, 'Mesa 5'), (6, 'Mesa 6'), (7, 'Mesa 7'), (8, 'Mesa 8'), (9, 'Mesa 9'), (10, 'Mesa 10')], default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='tasks.producto'),
        ),
    ]
