# Generated by Django 6.0.4 on 2026-05-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Pedido creado'), ('PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=20),
        ),
    ]
