# Generated by Django 6.0.4 on 2026-05-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_pedido_propina_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Pedido creado'), ('PREPARACION', 'En preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('COBRADO', 'Cobrado'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=20),
        ),
    ]
